<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class PowerlinkCRM
{
    private  $powerlink_crm_options ;
    public function __construct()
    {
        add_action( 'admin_menu', array( $this, 'powerlink_crm_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'powerlink_crm_page_init' ) );
    }
    
    public function powerlink_crm_add_plugin_page()
    {
        add_dashboard_page(
            'Powerlink CRM',
            // page_title
            'Powerlink CRM',
            // menu_title
            'manage_options',
            // capability
            'powerlink-crm',
            // menu_slug
            array( $this, 'powerlink_crm_create_admin_page' )
        );
    }
    
    public function powerlink_crm_create_admin_page()
    {
        $this->powerlink_crm_options = get_option( 'powerlink_crm_option_name' );
        ?>

		<div class="wrap">
			<?php 
        $path = __DIR__;
        // would contain '/rootdir/inc/public'
        $pathToImages = $path;
        $imgContent = $pathToImages . '\\powerlink-logo.png';
        // Read image path, convert to base64 encoding
        $imageData = base64_encode( file_get_contents( $imgContent ) );
        $src = 'data: ' . mime_content_type( $imgContent ) . ';base64,' . $imageData;
        ?>
			<img src="<?php 
        echo  $src ;
        ?>" width="200px"/>
			<h2>Elementor To Powerlink CRM</h2>
			
			<?php 
        printf(
            '<p>%s</p><p>%s <a href="https://app.powerlink.co.il/app/settings/integration/webintegrations" target="_blank">%s</a></p>',
            __( 'Please add your TokenID here:', 'elementor-forms-powerlink-action' ),
            __( 'You can find your token ', 'elementor-forms-powerlink-action' ),
            __( 'HERE', 'elementor-forms-powerlink-action' )
        );
        ?>
			<?php 
        settings_errors();
        ?>

			<form method="post" action="options.php">
				<?php 
        settings_fields( 'powerlink_crm_option_group' );
        do_settings_sections( 'powerlink-crm-admin' );
        submit_button();
        ?>
			</form>
		</div>
	<?php 
    }
    
    public function powerlink_crm_page_init()
    {
        register_setting(
            'powerlink_crm_option_group',
            // option_group
            'powerlink_crm_option_name',
            // option_name
            array( $this, 'powerlink_crm_sanitize' )
        );
        add_settings_section(
            'powerlink_crm_setting_section',
            // id
            'Settings',
            // title
            array( $this, 'powerlink_crm_section_info' ),
            // callback
            'powerlink-crm-admin'
        );
        add_settings_field(
            'token_id_0',
            // id
            'Token ID',
            // title
            array( $this, 'token_id_0_callback' ),
            // callback
            'powerlink-crm-admin',
            // page
            'powerlink_crm_setting_section'
        );
    }
    
    public function powerlink_crm_sanitize( $input )
    {
        $sanitary_values = array();
        if ( isset( $input['token_id_0'] ) ) {
            $sanitary_values['token_id_0'] = sanitize_text_field( $input['token_id_0'] );
        }
        return $sanitary_values;
    }
    
    public function powerlink_crm_section_info()
    {
    }
    
    public function token_id_0_callback()
    {
        printf( '<input class="regular-text" type="text" name="powerlink_crm_option_name[token_id_0]" id="token_id_0" value="%s">', ( isset( $this->powerlink_crm_options['token_id_0'] ) ? esc_attr( $this->powerlink_crm_options['token_id_0'] ) : '' ) );
    }

}
if ( is_admin() ) {
    $powerlink_crm = new PowerlinkCRM();
}
/* 
 * Retrieve this value with:
 * $powerlink_crm_options = get_option( 'powerlink_crm_option_name' ); // Array of All Options
 * $token_id_0 = $powerlink_crm_options['token_id_0']; // Token ID
 */